plot(x$Time,x$Sub_metering_1,type="l")
points(x$Time,x$Sub_metering_2,col="red",type="l")
points(x$Time,x$Sub_metering_3,col="blue",type="l")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),fill=c("black","red","blue"),horiz = FALSE)
dev.copy(png,file ="plot3.png")
png(filename="plot3.png", width=480,height=480)
dev.off()
